### ISSUE TITLE
Histograms need dynamic bin count 

### ISSUE THREAD

**Issue by pingpongkingkong** [bewuethr/advent_of_code#1]
Histograms seem to have a fixed bin count, drops everyone into the same bin if they answer within 15 minutes (it seems).

Could be dynamic bin count.

**Comment by bewuethr** [comment]
They are in fact one hour bins, the histogram was originally more of a "how are things distributed over the whole day" thing. Maybe another histogram for just the hour after midnight with much smaller bins?

**Comment by bewuethr** [comment]
Or (anonymous suggestion) use logarithmic x-scale.

**Comment by pingpongkingkong** [comment]
I like that idea, best of both worlds: simple and functional

**Comment by bewuethr** [comment]
Per-day graphs with submission times added in fabf9f4 and dd73045. Looking into making x-axis per day logarithmic, as time after midnight is still quite crowded.

**Comment by bewuethr** [comment]
Switched to log scale in 086e52a8
