### ISSUE TITLE
Feature Request: Histogram of time difference between submits

### ISSUE THREAD

**Issue by ivanpeng** [bewuethr/advent_of_code#9]
Star 1 and star 2 are measured in absolute difference from midnight, which isn't super helpful. What could be meaningful is the difference between the stars, as star 2 is historically "harder" than star 1. Possibly a histogram from this? Or a simple bar graph, unaggregated by day, also works too.

**Comment by bewuethr** [comment]
I'm going to add a column in the star 2 tables with the difference from the star 1 submission time.
